# path to root directory
# this requires REPO_ROOT environment variable to exist
root_dir: ${oc.env:REPO_ROOT}

# path to data directory
data_dir: ${oc.env:REPO_DATA_ROOT}

# path to logging directory
log_dir: ${oc.env:REPO_LOGS_ROOT}

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
