version: "3"

env:
  REPO_ROOT:
    sh: git rev-parse --show-toplevel

vars:
  VIRTUAL_ENV: "{{.REPO_ROOT}}/.venv"
  JOB_SCRIPTS_DIR: "{{.REPO_ROOT}}/src/job_scripts"
  TEMPLATES_DIR: "{{.JOB_SCRIPTS_DIR}}/templates"

  STANDARD_CPU_JOB_TEMPLATE: "standard_cpu_job_template.sh.jinja2"
  GPU_JOB_TEMPLATE: "gpu_job_template.sh.jinja2"
  QMC_JOBS_STARTER_TEMPLATE: "qmc_jobs_starter_template.sh.jinja2"

  PIPE_OUT_ROOT: "{{.REPO_ROOT}}/pipe_out"

dotenv: ['{{ .REPO_ROOT }}/.env']

tasks:

  setup:
    desc: Setup
    cmds:
      - mkdir -p {{ .PIPE_OUT_ROOT }}

  load_dataset:
    desc: Load a dataset
    deps:
      - setup
    env:
      VIRTUAL_ENV: '{{ .VIRTUAL_ENV }}'
    vars: 
      JOB_NAME: load_dataset
      MAX_DENSITY_ERROR: '{{ .MAX_DENSITY_ERROR | default 0.1 }}'

      _COMMAND: 'uv run python {{ .REPO_ROOT }}/src/dmb/data/bose_hubbard_2d/worm/scripts/load_dataset.py --simulations-dir {{ .REPO_ROOT }}/data/{{ .DATA_DIR }}/simulations --dataset-save-path {{ .REPO_ROOT }}/data/{{ .DATA_DIR }}/dataset/max_density_error_{{ .MAX_DENSITY_ERROR }} --max-density-error {{ .MAX_DENSITY_ERROR }} {{ .INCLUDE_TUNE_DIRS | default "" }}'
      
    cmds:
      - uv run jinja2 {{.TEMPLATES_DIR}}/{{ .STANDARD_CPU_JOB_TEMPLATE }} -D job_name={{ .JOB_NAME }} -D command='{{ ._COMMAND }}' -D venv_path='{{ .VIRTUAL_ENV }}' -D pipe_out_root='{{ .PIPE_OUT_ROOT }}' -D working_dir='{{ .REPO_ROOT }}' -D slurm_partition={{ .SLURM_DISPATCHER_PARTITION }} | sbatch

  load_dataset_box:
    desc: Load the box dataset
    cmds:
      - task: load_dataset
        vars:
          DATA_DIR: 'bose_hubbard_2d/box/1.0/0.1/41'
          MAX_DENSITY_ERROR: 0.3
          INCLUDE_TUNE_DIRS: '--include-tune-dirs'

  load_dataset_wedding_cake:
    desc: Load the wedding cake dataset
    cmds:
      - task: load_dataset
        vars:
          DATA_DIR: 'bose_hubbard_2d/wedding_cake/1.0/0.1/40/-2.0'

  load_dataset_mu_cut:
    desc: Load the mu cut dataset
    cmds:
      - task: load_dataset
        vars:
          DATA_DIR: 'bose_hubbard_2d/mu_cut/1.0/0.1/16'
          MAX_DENSITY_ERROR: 0.015

      - task: load_dataset
        vars:
          DATA_DIR: 'bose_hubbard_2d/mu_cut/1.0/0.25/16'
          MAX_DENSITY_ERROR: 0.015

  load_dataset_random:
    desc: Load the random dataset
    cmds:
      - task: load_dataset
        vars:
          DATA_DIR: 'bose_hubbard_2d/random'
          MAX_DENSITY_ERROR: 0.015
          INCLUDE_TUNE_DIRS: '--include-tune-dirs'


  run_qmc:
    desc: Run QMC
    deps:
      - setup
    env:
      VIRTUAL_ENV: '{{ .VIRTUAL_ENV }}'

    vars:
      NUMBER_OF_CONCURRENT_JOBS: '{{ .NUMBER_OF_CONCURRENT_JOBS | default 25 }}'
      SLURM_ARRAY_SIZE: '{{ .SLURM_ARRAY_SIZE | default 1 }}'
      MAX_DENSITY_ERROR: '{{ .MAX_DENSITY_ERROR | default 0.015 }}'

      _COMMAND:
        sh: echo "uv run python {{ .REPO_ROOT }}/src/dmb/data/bose_hubbard_2d/worm/scripts/{{ .QMC_SCRIPT_FILE }} {{ .QMC_TASK_ARGS | default "" }} --number_of_concurrent_jobs {{ .NUMBER_OF_CONCURRENT_JOBS }} --max_density_error {{ .MAX_DENSITY_ERROR }}"

    cmds:
      - uv run jinja2 {{.TEMPLATES_DIR}}/{{ .QMC_JOBS_STARTER_TEMPLATE }} -D qmc_task={{ .QMC_TASK }} -D command='{{ ._COMMAND }}' -D venv_path='{{ .VIRTUAL_ENV }}' -D slurm_array_size={{ .SLURM_ARRAY_SIZE }} -D pipe_out_root='{{ .PIPE_OUT_ROOT }}' -D working_dir='{{ .REPO_ROOT }}' -D slurm_partition={{ .SLURM_DISPATCHER_PARTITION }} -D worm_mpi_executable='{{ .WORM_MPI_EXECUTABLE }}' | sbatch
  
  run_qmc_random:
    desc: Run QMC on random potentials
    cmds:
      - task: run_qmc
        vars:
          QMC_TASK: random
          QMC_SCRIPT_FILE: create_random.py
          QMC_TASK_ARGS: '--type random --number_of_samples 250' #--U_on_max 0.4 --V_nn_z_min 0.85 --V_nn_z_max 1.15 --mu_offset_min 1.5
          NUMBER_OF_CONCURRENT_JOBS: 1 #50
          NUMBER_OF_SAMPLES: 1 #250
          SLURM_ARRAY_SIZE: 1

  run_qmc_box:
    desc: Run QMC on the box potential
    cmds:
      - task: run_qmc
        vars:
          QMC_TASK: box
          QMC_SCRIPT_FILE: sandbox/box.py
          QMC_TASK_ARGS: '--tau_max_threshold 25'
          MAX_DENSITY_ERROR: 0.03
          NUMBER_OF_CONCURRENT_JOBS: 25

  run_qmc_wedding_cake:
    desc: Run QMC on the wedding cake potential
    cmds:
      - task: run_qmc
        vars:
          QMC_TASK: wedding_cake
          QMC_SCRIPT_FILE: sandbox/wedding_cake.py
          NUMBER_OF_CONCURRENT_JOBS: 10

  run_qmc_mu_cut:
    desc: Run QMC on the mu cut potential
    cmds:
      - task: run_qmc
        vars:
          QMC_TASK: mu_cut
          QMC_SCRIPT_FILE: sandbox/mu_cut.py
          QMC_TASK_ARGS: '--L 16 --muU_num_steps 50 --muU_min 0.0 --muU_max 3.0 --zVU 1.0 --ztU 0.25'
          NUMBER_OF_CONCURRENT_JOBS: 25

      - task: run_qmc
        vars:
          QMC_TASK: mu_cut
          QMC_SCRIPT_FILE: sandbox/mu_cut.py
          QMC_TASK_ARGS: '--L 16 --muU_num_steps 50 --muU_min 0.0 --muU_max 3.0 --zVU 1.0 --ztU 0.1'
          NUMBER_OF_CONCURRENT_JOBS: 25

  run_qmc_phase_diagram:
    desc: Run QMC on the phase diagram
    cmds:
      - task: run_qmc
        vars:
          QMC_TASK: phase_diagram
          QMC_SCRIPT_FILE: phase_diagram/create.py
          QMC_TASK_ARGS: '--L 16 --min_distance_between_samples_U_inv 0.1 --min_distance_between_samples_mu 0.1 --muU_min 0.0 --muU_max 3.0'
          NUMBER_OF_CONCURRENT_JOBS: 20