name: "Setup Python Environment"
description: "Setup Python and install dependencies"
runs:
  using: "composite"

  steps:
    - uses: actions/checkout@v4

    - name: Setup Cache
      id: setup-cache
      uses: actions/cache@v4
      with:
        path: |
          ${{ github.workspace }}/.venv
        key: ${{ runner.os }}-uv-${{ hashFiles('uv.lock', 'pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install tools
      run: |
        sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b "${{ github.workspace }}/.local/bin"
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "/home/runner/work/dmb/dmb/.local/bin" >> $GITHUB_PATH
        echo "/home/runner/.cargo/bin" >> $GITHUB_PATH
      shell: bash

    - name: Install dependencies
      if: steps.setup-cache.outputs.cache-hit != 'true'
      run: DEVICE=cpu task install
      shell: bash

    - name: Create .cache directory
      run: mkdir -p ${{ github.workspace }}/.cache
      shell: bash
