[tool.poetry]
name = "dmb"
version = "0.1.0"
description = ""
authors = ["fabian <dechent.fabian@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<3.12"
torch = ">=2.0.0, !=2.0.1, !=2.1.0"
numpy = "^1.24.3"
scipy = "^1.10.1"
matplotlib = "^3.7.1"
git-python = "^1.0.3"
joblib = "^1.2.0"
orjson = "^3.8.12"
jupyterlab = "^4.0.0"
h5py = "^3.8.0"
fyeldgenerator = {git = "https://github.com/cphyc/FyeldGenerator.git"}
hydra-core = "^1.3.2"
python-dotenv = "^1.0.0"
rich = "^13.4.2"
tensorboard = "^2.13.0"
pytest = "^7.4.2"
lightning = "^2.1.0"
torchvision = "0.15.1"
ninja = "^1.11.1.1"
isort = "^5.12.0"
black = {extras = ["jupyter"], version = "^23.11.0"}
ruff = "^0.1.6"
mypy = "^1.7.1"
auto-correlation = {path = "auto-correlation"}

[build-system]
requires = ["poetry-core", "setuptools>=40.8.0", "wheel", "torch>=2.0.0, !=2.0.1, !=2.1.0"]
build-backend = "poetry.core.masonry.api"
