version: "3"

vars:
  PYTHON_CODE_DIRS: src/dmb src/tests src/scripts #src/auto-correlation
  REPO_ROOT:
    sh: git rev-parse --show-toplevel

  PLATFORM:
    sh: uname -s

tasks:
  install:
    desc:
      Install dependencies. Poetry cannot handle the torch installation properly on
      multiple hardware platforms.
    vars:
      DEVICE: '{{ .DEVICE | default "cpu" }}' # cpu or cu121
    cmds:
      - uv sync
      - |
        if [ "{{ .PLATFORM }}" = "Darwin" ]; then
          uv pip install torch==2.4.1 torchvision==0.19.1
        fi
        if [ "{{ .PLATFORM }}" = "Linux" ]; then
          if [ "{{ .DEVICE }}" = "cpu" ];
          then
            uv add torch==2.4.1 torchvision==0.19.1
          else
            uv pip install torch==2.4.1+cu124 torchvision==0.19.1 --index-url https://download.pytorch.org/whl/cu124
          fi
        fi

  format:
    desc: Format the code
    cmds:
      - uv run yapf -i --recursive {{ .PYTHON_CODE_DIRS }}
      - uv run isort {{ .PYTHON_CODE_DIRS }}

  lint:
    desc: Lint the code
    vars:
      YAPF_FILES:
        sh: git ls-files | grep '.py' | tr '\n' ' '
    cmds:
      - uv run isort --check-only {{ .PYTHON_CODE_DIRS }}
      - >
        if [ -n "{{ .FILES }}" ]; then 
          yapf --diff {{ .FILES }}; 
        fi
      - uv run mypy {{ .PYTHON_CODE_DIRS }}
      - uv run pylint -v {{ .PYTHON_CODE_DIRS }}

  test:
    desc: Run tests
    vars:
      MARK: '{{ .MARK | default "" }}'
    cmds:
      - uv run pytest -vv -m "{{ .MARK }}" --basetemp={{ .REPO_ROOT }}/.cache/pytest_tmp

  licenses:
    desc: List licenses of dependencies
    cmds:
      - uv run pip-licenses --from=mixed --order=license --summary
