version: "3"

env:
  REPO_ROOT:
    sh: git rev-parse --show-toplevel

  VIRTUAL_ENV: "{{ .REPO_ROOT }}/.venv"
  UV_CACHE_DIR: "{{ .REPO_ROOT }}/.cache/uv"

  PATH:
    sh: echo {{ .VIRTUAL_ENV }}/bin:$PATH

vars:
  PLATFORM:
    sh: uname -s | tr '[:upper:]' '[:lower:]'

  PYTHON_CODE_DIRS: "src/dmb src/tests"


tasks:
  install:
    desc: "Install dependencies"
    vars:
      EXTRAS: '{{ .EXTRAS | default "--extra cu124" }}'
      GROUPS: '{{ .GROUPS | default "--all-groups" }}'
    cmds:
      - uv sync {{ .GROUPS }} {{ .EXTRAS }}

  format:
    desc: Format the code
    cmds:
      - ruff format {{ .PYTHON_CODE_DIRS }}
      - isort {{ .PYTHON_CODE_DIRS }}

  lint:
    desc: Lint the code
    cmds:
      - isort --check-only {{ .PYTHON_CODE_DIRS }}
      - ruff check {{ .PYTHON_CODE_DIRS }}
      - mypy {{ .PYTHON_CODE_DIRS }}

  test:
    desc: Run tests
    vars:
      MARK: '{{ .MARK | default "not requires_worm" }}'
    cmds:
      - pytest -m "{{ .MARK }}" --basetemp={{ .REPO_ROOT }}/.cache/pytest_tmp
      - |
        if [ -z "$CI" ]; then
          find {{ .REPO_ROOT }} -maxdepth 1 -type f -name '.coverage*' -delete
        fi

  licenses:
    desc: List licenses of dependencies
    cmds:
      - pip-licenses --from=mixed --order=license --summary
