_target_: dmb.data.bose_hubbard_2d.worm.datamodule.BoseHubbard2dDataModule

dataset:
  _target_: dmb.data.bose_hubbard_2d.worm.dataset.BoseHubbard2dDataset
  transforms: dmb.data.bose_hubbard_2d.transforms.BoseHubbard2dTransforms
  dataset_dir_path: ???

split:
  _target_: dmb.data.split.Split.from_file
  file_path: ???

batch_size: 32
num_workers: 4
pin_memory: True

