_target_: dmb.data.bose_hubbard_2d.worm.datamodule.BoseHubbardDataModule

data_dir: ${paths.data_dir}/bose_hubbard_2d
batch_size: 512
num_workers: 4
clean: True
base_transforms: null
train_transforms: null
max_density_error: 0.015
reload: False 
include_tune_dirs: False

train_val_test_split: [0.94, 0.05, 0.01]