_target_: dmb.data.bose_hubbard_2d_pyalps.datamodule.DataModule2d

batch_size: 512
num_workers: 4

dataset:
  _target_: dmb.data.bose_hubbard_2d_pyalps.dataset.DataSet2d.loader

  task: bosons_ztu_0_1_zvu_075_175_T_1_skip_300_amplitude_1_5_even
  sizes: [6,8,10,12,14,16]
  add_parameters_as_channel: True 
  rescaled: False
  rescale_output: False
  data_fraction: 1.0 
  test_split: 0.05 
  ztU_range: null 
  only_converged: False 
  limit_energy: null 
  ignore_large_real_sweeps: False
