_target_: dmb.data.split.Split.from_dataset

dataset:
  _target_: dmb.data.bose_hubbard_2d.worm.dataset.BoseHubbard2dDataset
  dataset_dir_path: ???
  transforms: 
    _target_: dmb.data.bose_hubbard_2d.transforms.BoseHubbard2dTransforms

  sample_filter_strategy:
    _target_: dmb.data.bose_hubbard_2d.worm.dataset.BoseHubbard2dSampleFilterStrategy
    ztU_range: [0.05, 1.0]
    muU_range: [-0.05, 3.0]
    zVU_range: [0.75, 1.75]
    L_range: [2, 20]
    max_density_error: 0.015

split_fractions: 
  train: 0.96
  val: 0.02
  test: 0.02

split_strategy:
  _target_: dmb.data.bose_hubbard_2d.worm.dataset.WormSimulationsSplitStrategy
  