_target_: dmb.data.split.Split.from_dataset

dataset:
  _target_: dmb.data.bose_hubbard_2d.worm.dataset.BoseHubbard2dDataset
  dataset_dir_path: ???
  transforms: 
    _target_: dmb.data.bose_hubbard_2d.transforms.BoseHubbard2dTransforms

split_fractions: 
  train: 0.96
  val: 0.02
  test: 0.02

split_strategy:
  _target_: dmb.data.bose_hubbard_2d.worm.split.WormSimulationsSplitStrategy
  