_target_: dmb.data.split.Split.from_dataset

dataset:
  _target_: dmb.data.bose_hubbard_2d.worm.dataset.BoseHubbardDataset
  
  data_dir: ${paths.data_dir}/bose_hubbard_2d
  max_density_error: 0.015
  reload: False
  transforms: 
    _target_: dmb.data.bose_hubbard_2d.transforms.BoseHubbard2dTransforms

split_fractions: 
  train: 0.96
  val: 0.02
  test: 0.02