defaults:
  - _self_

model_summary:
  _target_: lightning.pytorch.callbacks.ModelSummary
  max_depth: -1

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: null
  log_momentum: False

plotting:
  _target_: dmb.scripts.train.callbacks.PlottingCallback
  plot_interval: 100

progress_bar:
  _target_: lightning.pytorch.callbacks.TQDMProgressBar
  refresh_rate: 50
  
# swa:
#   _target_: lightning.pytorch.callbacks.StochasticWeightAveraging
#   swa_lrs: 1e-2
