defaults:
  - _self_

model_summary:
  _target_: lightning.pytorch.callbacks.ModelSummary
  max_depth: -1

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  logging_interval: null
  log_momentum: False

progress_bar:
  _target_: lightning.pytorch.callbacks.TQDMProgressBar
  refresh_rate: 50

plotting:
  _target_: dmb.scripts.invert.callbacks.StoreResultsCallback