_target_: dmb.model.lit_dmb_model.LitDMBModel

defaults:
  - model: dmb_model

loss:
  _target_: dmb.model.loss.MSELoss
  
optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001

lr_scheduler:
  scheduler:
    _target_: ???
    _partial_: true

  monitor: train/mse
  interval: epoch
  frequency: 1

metrics:
  _target_: torchmetrics.MetricCollection
  _convert_: all # torchmetrics expects a dictionary of metrics
  metrics:
    mse:
      _target_: dmb.model.metrics.MSE
    msle:
      _target_: dmb.model.metrics.MSLE

evaluation_data_metrics:
  _target_: torchmetrics.MetricCollection
  _convert_: all # torchmetrics expects a dictionary of metrics
  metrics:
    mse:
      _target_: dmb.model.metrics.MSE
    msle:
      _target_: dmb.model.metrics.MSLE

weights_checkpoint: null