name: CI jobs

env:
  TASK_X_ENV_PRECEDENCE: "1"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  setup:
    name: Update dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup
        uses: ./.github/actions/setup

  lint:
    name: Lint
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup
        uses: ./.github/actions/setup

      - name: Lint code
        run: |
          task lint

  test:
    name: Test
    runs-on: ubuntu-latest

    needs: setup

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run setup
        uses: ./.github/actions/setup

      - name: Run tests
        run: |
          task test MARK="not requires_worm"
